#!/usr/bin/env python2
#
# Read JSON from stdin, and get a dict key as command line argument.
# Extract the value corresponding to the key, write to standard output.
#
# Copyright 2015, 2016 Suomen Tilaajavastuu Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import json, sys, os

obj = json.load(sys.stdin)
key = sys.argv[1]

sys.stderr.write("obj: %r\n" % repr(obj))
sys.stderr.write("key: %r\n" % repr(key))

assert type(obj) is dict, "expected a dictionary"
assert key in obj, "expected dictionary to have key %s" % key
assert type(obj[key]) in [str, unicode], "expected value to be a string"

sys.stdout.write(obj[key])
