#!/bin/bash
#
# Test jsonmatch a bit. This script needs to exit with 0 for the tests
# to pass.
#
# Copyright 2015, 2016 Suomen Tilaajavastuu Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -eux


# Match exact dict value.
./jsonmatch whole '{"foo": "bar"}' <<< '{"foo": "bar"}'

# Match against dict with missing key.
! ./jsonmatch whole '{"foo": "bar"}' <<< '{}'

# Match against dict with additional extra key.
./jsonmatch whole '{"foo": "bar"}' <<< '{"foo": "bar", "yo": 1}'

# Match exact list value.
./jsonmatch whole '{"foo": ["bar"]}' <<< '{"foo": ["bar"]}'

# Match against list of different length.
! ./jsonmatch whole '{"foo": ["bar"]}' <<< '{"foo": []}'

# Match against's list with same length, but different content.
! ./jsonmatch whole '{"foo": ["bar"]}' <<< '{"foo": ["yo"]}'

# Match multi-level dicts.
./jsonmatch whole '{"foo": {"bar": 1}}' <<< '{"foo": {"bar": 1}}'
! ./jsonmatch whole '{"foo": {"bar": 1}}' <<< '{"foo": {"foo": 1}}'
! ./jsonmatch whole '{"foo": {"bar": 1}}' <<< '{"foo": {"bar": 2}}'

# Match against an item in the list.
./jsonmatch list-item '1' foo <<< '{"foo": [1]}'
! ./jsonmatch list-item '2' foo <<< '{"foo": [1]}'
./jsonmatch list-item '{"name": "James"}' aliases \
  <<< '{"aliases": [{"name": "blah"}, {"name": "James"}]}'
