#!/bin/bash
#
# Test the Qvarn API.
# Argument: URL of the API
#
# Copyright 2015, 2016 Suomen Tilaajavastuu Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -eu

API_URL="$1"
shift
TEMP="$(mktemp)"

function clean
{
  rm -f "$TEMP"
}
trap clean EXIT

# When yarn runs createtoken, it sets HOME to a temporary directory. Thus,
# createtoken won't find its config file automatically. We tell it, via
# yarn's --env, where to find it.
CONF="${QVARN_CREATETOKEN_CONF:=$HOME/.config/qvarn/createtoken.conf}"

# Run yarn.
sed '/^    *EXAMPLE/,/^ *$/d' *.yarn > "$TEMP"
yarn -s yarn.sh \
     --env "API_URL=$API_URL" \
     --env "QVARN_CREATETOKEN_CONF=$CONF" \
     "$TEMP" "$@"
