#!/bin/bash
#
# Test jsonextract a bit. This script needs to exit with 0 for the tests
# to pass.
#
# Copyright 2015, 2016 Suomen Tilaajavastuu Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


set -eux

# Input is not valid JSON.
! ./jsonextract foo <<< 'blahbla!'

# Input is not a dict.
! ./jsonextract foo <<< '123'

# Given key is not in input.
! ./jsonextract foo <<< '{}'

# Value is not a string.
! ./jsonextract foo <<< '{"foo": 123}'

# All OK.
test "$(./jsonextract foo <<< '{"foo": "bar"}')" = bar
