#!/bin/bash
#
# Test the Qvarn API.
# Argument: URL of the API

set -eu

API_URL="$1"
shift
TEMP="$(mktemp)"

function clean
{
  rm -f "$TEMP"
}
trap clean EXIT

# When yarn runs createtoken, it sets HOME to a temporary directory. Thus,
# createtoken won't find its config file automatically. We tell it, via
# yarn's --env, where to find it.
CONF="${QVARN_CREATETOKEN_CONF:=$HOME/.config/qvarn/createtoken.conf}"

# Run yarn.
sed '/^    *EXAMPLE/,/^ *$/d' *.yarn > "$TEMP"
yarn -s yarn.sh \
     --env "API_URL=$API_URL" \
     --env "QVARN_CREATETOKEN_CONF=$CONF" \
     "$TEMP" "$@"
