#!/bin/sh
#
# Prepare Qvarn databases by creating/modifying/dropping tables to
# current schema. This MUST NOT be run while Qvarn is running
# normally.

set -eu

for x in $(ls /usr/lib/unified-api-backend)
do
    "/usr/lib/unified-api-backend/$x" "--config=/etc/qvarn/$x.conf" --prepare-storage
done
