#!/usr/bin/env python2
#
# qvarn-backend - implement all the Qvarn resources
#
# Copyright 2016  QvarnLabs AB
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import os
import yaml

import qvarn


specdir = '/etc/qvarn'


def version():
    return {
        'api': {
            'version': qvarn.__version__,
        },
        'implementation': {
            'name': 'Qvarn',
            'version': qvarn.__version__,
        },
    }


def setup_version_resource(app):
    vs = qvarn.VersionedStorage()
    vs.set_resource_type(u'version')
    app.add_versioned_storage(vs)

    resource = qvarn.SimpleResource()
    resource.set_path(u'/version', version)
    app.add_resource(resource)


app = qvarn.BackendApplication()
setup_version_resource(app)
application = app.prepare_for_uwsgi(specdir)
