#!/usr/bin/env python
# slog-demo - show off structured logging
#
# Copyright 2016  QvarnLabs Ab
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import qvarn


writer = qvarn.FileSlogWriter()
writer.set_filename_prefix('slog-demo')

log = qvarn.StructuredLog()
log.add_log_writer(writer)
log.set_context('demo')
log.log('intro', msg_text='hello, there, this is a structured log file')
log.log('intro', msg_text='each line is JSON')
log.close()
