#!/bin/sh
#
# start-backend-app - start a backend application
#
# This starts the application, giving it the correct database and log
# file location, and capturing startup information. This is meant to be
# run in a deployed system, not on a development machine.
#
# Copyright 2015 Suomen Tilaajavastuu Oy
# All rights reserved.



set -eu

app="/usr/lib/unified-api-backend/$1"
config="--config=/etc/qvarn/$1.conf"
startlog="/var/log/unified-api-backend/$1.start.log"

# We blithely put the lock file in /run/lighttpd, because
# a) we're running under lighttpd
# b) it has the right permissions.
# This should possibly be fixed by creating a /run/qvarn
# with the right permissions in a suitable systemd unit.
flock /run/lighttpd/qvarn.lock "$app" "$config" --prepare-storage

exec "$app" "$config" >> "$startlog" 2>&1
