#!/usr/bin/python2
#
# Reads scopes from STDIN, gets JWT from gluu and writes it to STDOUT

import sys, requests, base64

scopes = sys.stdin.read().strip()
token_endpoint_url = u'{}/auth/token'.format(sys.argv[1])
client_id = u'@!D0B3.42FF.3A77.681D!0001!0105.03F6!0008!5B05.DDAB'
client_secret = u'secret'

basic_auth_token = base64.standard_b64encode(client_id + u':' + client_secret)

response = requests.post(token_endpoint_url, {
    u'grant_type': u'client_credentials',
    u'scope': scopes
}, headers={
    u'Authorization': u'Basic ' + basic_auth_token
}, verify=False)

if not response.ok:
    sys.stderr.write(str(response.status_code) + u'\n')
    sys.stderr.write(str(response.headers) + u'\n')
    sys.stderr.write(str(response.json()) + u'\n')
    sys.exit(1)

sys.stdout.write(response.json()[u'access_token'] + u'\n')
