#!/usr/bin/env python2
#
# src/competence-types - implement the /competence_types resource
#
# Copyright 2015, 2016 Suomen Tilaajavastuu Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import qvarn


resource_type = u'competence_type'


competence_type_prototype_v0 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
}


competence_type_prototype_current = competence_type_prototype_v1 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
    u'competence_type_id': u'',
    u'names': [
        {
            u'locale': u'',
            u'name': u''
        }
    ],
    u'descriptions': [
        {
            u'locale': u'',
            u'description': u''
        }
    ]
}


def validate_competence_type(obj):
    pass


def setup():
    vs = qvarn.VersionedStorage()
    vs.set_resource_type(resource_type)

    vs.start_version(u'v0', None)
    vs.add_prototype(competence_type_prototype_v0)

    vs.start_version(u'v1', None)
    vs.add_prototype(competence_type_prototype_v1)
    vs.add_prototype(qvarn.listener_prototype, auxtable=u'listener')
    vs.add_prototype(
        qvarn.notification_prototype, auxtable=u'notification')

    app = qvarn.BackendApplication()
    app.set_versioned_storage(vs)

    listener_resource = qvarn.ListenerResource()
    listener_resource.set_top_resource_path(
        resource_type, u'/competence_types')
    app.add_resource(listener_resource)

    resource = qvarn.ListResource()
    resource.set_path(u'/competence_types')
    resource.set_item_type(resource_type)
    resource.set_item_prototype(competence_type_prototype_current)
    resource.set_item_validator(validate_competence_type)
    resource.set_listener(listener_resource)
    app.add_resource(resource)

    return app.prepare_for_uwsgi()


application = setup()
