#!/usr/bin/env python2
#
# src/competences - implement the /competences resource
#
# Copyright 2015, 2016 Suomen Tilaajavastuu Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import qvarn


competence_prototype_v0 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
}


competence_prototype_v1 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
    u'employee_person_id': u'',
    u'employer_org_id': u'',
    u'valid_from_date': u'',
    u'valid_until_date': u'',
    u'competence_type_id': u'',
    u'competence_card_id': u'',
    u'competence_card_holder_names': [
        {
            u'full_name': u'',
            u'sort_key': u'',
            u'given_names': [u''],
            u'surnames': [u''],
        },
    ],
}


competence_prototype_current = competence_prototype_v2 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
    u'employee_person_id': u'',
    u'employer_org_id': u'',
    u'valid_from_date': u'',
    u'valid_until_date': u'',
    u'competence_type_id': u'',
    u'granted_by_org_id': u'',
    u'competence_registry_id': u'',
    u'competence_card_id': u'',
    u'competence_card_holder_names': [
        {
            u'full_name': u'',
            u'sort_key': u'',
            u'given_names': [u''],
            u'surnames': [u''],
        },
    ],
    u'competence_trainer': u'',
    u'validation_status': u'',
}


competence_sync_prototype = {
    u'sync_id': u'',
    u'sync_revision': u'',
}


resource_type_spec = {
    u'path': u'/competences',
    u'type': u'competence',
    u'versions': [
        {
            u'version': u'v0',
            u'prototype': competence_prototype_v0,
        },
        {
            u'version': u'v1',
            u'prototype': competence_prototype_v1,
            u'subpaths': {
                u'sync': {
                    u'prototype': competence_sync_prototype,
                },
            },
        },
        {
            u'version': u'v2',
            u'prototype': competence_prototype_v2,
            u'subpaths': {
                u'sync': {
                    u'prototype': competence_sync_prototype,
                },
            },
        },
    ],
}


application = qvarn.create_resource_server(resource_type_spec)
