#!/usr/bin/env python2
#
# src/competence-types - implement the /competence_types resource
#
# Copyright 2015 Suomen Tilaajavastuu Oy
# All rights reserved.


import unifiedapi


competence_type_prototype = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
    u'competence_type_id': u'',
    u'names': [
        {
            u'locale': u'',
            u'name': u''
        }
    ],
    u'descriptions': [
        {
            u'locale': u'',
            u'description': u''
        }
    ]
}


class CreateCompetenceTypesTables_v1(unifiedapi.StoragePreparationStep):

    def run(self, db):
        db.create_table(
            u'competence_type',
            (u'type', unicode),
            (u'id', unicode),
            (u'revision', unicode),
            (u'competence_type_id', unicode))

        db.create_table(
            u'competence_type_names',
            (u'id', unicode),
            (u'list_pos', int),
            (u'locale', unicode),
            (u'name', unicode))

        db.create_table(
            u'competence_type_descriptions',
            (u'id', unicode),
            (u'list_pos', int),
            (u'locale', unicode),
            (u'description', unicode))

        db.create_table(
            u'listener',
            (u'type', unicode),
            (u'id', unicode),
            (u'revision', unicode),
            (u'notify_of_new', bool))

        db.create_table(
            u'listener_listen_on',
            (u'id', unicode),
            (u'list_pos', int),
            (u'listen_on', unicode))

        db.create_table(
            u'notification',
            (u'type', unicode),
            (u'id', unicode),
            (u'listener_id', unicode),
            (u'revision', unicode),
            (u'resource_id', unicode),
            (u'resource_revision', unicode),
            (u'resource_change', unicode),
            (u'last_modified', int))


def validate_competence_type(obj):
    pass


if __name__ == '__main__':
    app = unifiedapi.BackendApplication()

    prep = unifiedapi.StoragePreparer()
    prep.add_step(
        u'create_competence_types_tables_v1', CreateCompetenceTypesTables_v1())
    app.set_storage_preparer(prep)

    listener_resource = unifiedapi.ListenerResource()
    listener_resource.set_top_resource_path(u'/competence_types')
    app.add_resource(listener_resource)

    resource = unifiedapi.ListResource()
    resource.set_path(u'/competence_types')
    resource.set_item_type(u'competence_type')
    resource.set_item_prototype(competence_type_prototype)
    resource.set_item_validator(validate_competence_type)
    resource.set_listener(listener_resource)
    app.add_resource(resource)

    app.run()
