#!/usr/bin/env python2
#
# src/contracts.py - implement the /contracts resource
#
# Copyright 2015, 2016 Suomen Tilaajavastuu Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import qvarn


resource_type = u'contract'


contract_prototype_v0 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
}


contract_prototype_v1 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
    u'contract_type': u'',
    u'start_date': u'',
    u'end_date': u'',
    u'date_created': u'',
    u'date_updated': u'',
    u'contract_parties': [
        {
            u'type': u'',
            u'resource_id': u'',
            u'role': u'',
            u'contacts': [
                {
                    u'contact_type': u'',
                    u'contact_source': u'',
                    u'contact_timestamp': u'',
                    u'phone_number': u'',
                    u'email_address': u'',
                    u'full_address': u'',
                    u'country': u'',
                    u'address_lines': [u''],
                    u'post_code': u'',
                    u'post_area': u'',
                },
            ],
            u'username': u'',
            u'user_role': u'',
        },
    ],
    u'right_to_work_based_on': u'',
    u'id06_issuer_requires_bankid': False,
    u'id06_contact_name': u'',
    u'id06_contact_email': u'',
    u'contract_state': u'',
    u'preferred_language': u'',
    u'contract_state_history': [
        {
            u'state': u'',
            u'modified_by': u'',
            u'modification_timestamp': u'',
        },
    ],
    u'signers': [
        {
            u'signer': u'',
            u'signing_request_timestamp': u'',
            u'signing_request_message': u'',
            u'signing_timestamp': u'',
        },
    ],
}


contract_prototype_v2 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
    u'contract_type': u'',
    u'start_date': u'',
    u'end_date': u'',
    u'date_created': u'',
    u'date_updated': u'',
    u'contract_parties': [
        {
            u'type': u'',
            u'resource_id': u'',
            u'role': u'',
            u'contacts': [
                {
                    u'contact_type': u'',
                    u'contact_roles': u'',
                    u'contact_source': u'',
                    u'contact_timestamp': u'',
                    u'phone_number': u'',
                    u'email_address': u'',
                    u'full_address': u'',
                    u'country': u'',
                    u'address_lines': [u''],
                    u'post_code': u'',
                    u'post_area': u'',
                },
            ],
            u'username': u'',
            u'user_role': u'',
        },
    ],
    u'right_to_work_based_on': u'',
    u'id06_issuer_requires_bankid': False,
    u'id06_contact_name': u'',
    u'id06_contact_email': u'',
    u'contract_state': u'',
    u'preferred_language': u'',
    u'contract_state_history': [
        {
            u'state': u'',
            u'modified_by': u'',
            u'modification_timestamp': u'',
        },
    ],
    u'signers': [
        {
            u'signer': u'',
            u'signing_request_timestamp': u'',
            u'signing_request_message': u'',
            u'signing_timestamp': u'',
        },
    ],
}


contract_prototype_v3 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
    u'contract_type': u'',
    u'start_date': u'',
    u'end_date': u'',
    u'date_created': u'',
    u'date_updated': u'',
    u'contract_parties': [
        {
            u'type': u'',
            u'resource_id': u'',
            u'role': u'',
            u'username': u'',
            u'user_role': u'',
        },
    ],
    u'right_to_work_based_on': u'',
    u'id06_issuer_requires_bankid': False,
    u'id06_contact_name': u'',
    u'id06_contact_email': u'',
    u'contract_state': u'',
    u'preferred_language': u'',
    u'contract_state_history': [
        {
            u'state': u'',
            u'modified_by': u'',
            u'modification_timestamp': u'',
        },
    ],
    u'signers': [
        {
            u'signer': u'',
            u'signing_request_timestamp': u'',
            u'signing_request_message': u'',
            u'signing_timestamp': u'',
        },
    ],
}


contract_prototype_v4 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
    u'contract_type': u'',
    u'start_date': u'',
    u'end_date': u'',
    u'date_created': u'',
    u'date_updated': u'',
    u'contract_parties': [
        {
            u'type': u'',
            u'resource_id': u'',
            u'role': u'',
            u'username': u'',
            u'user_role': u'',
            u'contacts': [
                {
                    u'contact_type': u'',
                    u'contact_roles': u'',
                    u'contact_source': u'',
                    u'contact_timestamp': u'',
                    u'phone_number': u'',
                    u'email_address': u'',
                    u'full_address': u'',
                    u'country': u'',
                    u'address_lines': [u''],
                    u'post_code': u'',
                    u'post_area': u'',
                },
            ],
        },
    ],
    u'right_to_work_based_on': u'',
    u'id06_issuer_requires_bankid': False,
    u'id06_contact_name': u'',
    u'id06_contact_email': u'',
    u'contract_state': u'',
    u'preferred_language': u'',
    u'contract_state_history': [
        {
            u'state': u'',
            u'modified_by': u'',
            u'modification_timestamp': u'',
        },
    ],
    u'signers': [
        {
            u'signer': u'',
            u'signing_request_timestamp': u'',
            u'signing_request_message': u'',
            u'signing_timestamp': u'',
        },
    ],
}


contract_prototype_current = contract_prototype_v5 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
    u'contract_type': u'',
    u'start_date': u'',
    u'end_date': u'',
    u'date_created': u'',
    u'date_updated': u'',
    u'contract_parties': [
        {
            u'type': u'',
            u'resource_id': u'',
            u'role': u'',
            u'username': u'',
            u'user_role': u'',
            u'contacts': [
                {
                    u'contact_type': u'',
                    u'contact_roles': u'',
                    u'contact_source': u'',
                    u'contact_timestamp': u'',
                    u'phone_number': u'',
                    u'email_address': u'',
                    u'full_address': u'',
                    u'country': u'',
                    u'address_lines': [u''],
                    u'post_code': u'',
                    u'post_area': u'',
                },
            ],
            u'permissions': [
                {
                    u'permission_name': u'',
                }
            ],
            u'global_permissions': [
                {
                    u'permission_name': u'',
                }
            ],
        },
    ],
    u'right_to_work_based_on': u'',
    u'id06_issuer_requires_bankid': False,
    u'id06_contact_name': u'',
    u'id06_contact_email': u'',
    u'contract_state': u'',
    u'preferred_language': u'',
    u'contract_state_history': [
        {
            u'state': u'',
            u'modified_by': u'',
            u'modification_timestamp': u'',
        },
    ],
    u'signers': [
        {
            u'signer': u'',
            u'signing_request_timestamp': u'',
            u'signing_request_message': u'',
            u'signing_timestamp': u'',
        },
    ],
}


contract_document_prototype = {
    u'body': buffer(''),
    u'content_type': u'',
}


contract_sync_prototype = {
    u'sync_sources': [
        {
            u'sync_source': u'',
            u'sync_id': u'',
        },
    ],
    u'sync_revision': u'',
}


class InvalidContractType(qvarn.ValidationError):

    msg = u'Contract {id} contract type is invalid'


class InvalidPartyType(qvarn.ValidationError):

    msg = u'Contract {id} contract party party type is invalid'


class InvalidRightToWorkBasedOn(qvarn.ValidationError):

    msg = u'Contract {id} right to work based on is invalid'


def validate_contract(obj):
    allowed_contract_types = [
        u'employment',
        u'induction',
        u'ID06_cards',
        u'SBCC_account',
        u'tilaajavastuu_account',
        u'service_application',
        u'taito_subscription'
    ]
    if obj[u'contract_type'] not in allowed_contract_types:
        raise InvalidContractType(id=obj[u'id'])

    if obj[u'contract_type'] == u'employment':
        for party in obj[u'contract_parties']:
            if party[u'role'] not in [u'employer', u'employee']:
                raise InvalidPartyType(id=obj[u'id'])

    if obj[u'contract_type'] == u'induction':
        for party in obj[u'contract_parties']:
            if party[u'role'] not in [u'inductor', u'inductee']:
                raise InvalidPartyType(id=obj[u'id'])

    if obj[u'contract_type'] in (u'tilaajavastuu_account', u'SBCC_account'):
        for party in obj[u'contract_parties']:
            if party[u'role'] not in [u'user', u'target']:
                raise InvalidPartyType(id=obj[u'id'])

    if obj[u'contract_type'] == u'service_application':
        for party in obj[u'contract_parties']:
            if party[u'role'] not in [u'applicant']:
                raise InvalidPartyType(id=obj[u'id'])

    if obj[u'contract_type'] == u'ID06_cards':
        for party in obj[u'contract_parties']:
            if party[u'role'] not in [
                    u'issuer', u'supplier', u'issuer_contact'
            ]:
                raise InvalidPartyType(id=obj[u'id'])

    if obj[u'contract_type'] == u'taito_subscription':
        for party in obj[u'contract_parties']:
            if party[u'role'] not in [u'customer']:
                raise InvalidPartyType(id=obj[u'id'])

    if (obj[u'contract_type'] == u'employment' or
            obj[u'contract_type'] == u'induction'):
        allowed_rights = [u'eea_citizen', u'residence_permit', u'other']
        if obj[u'right_to_work_based_on'] not in allowed_rights:
            raise InvalidRightToWorkBasedOn(id=obj[u'id'])


def setup():
    vs = qvarn.VersionedStorage()
    vs.set_resource_type(resource_type)

    vs.start_version(u'v0', None)
    vs.add_prototype(contract_prototype_v0)

    vs.start_version(u'v1', None)
    vs.add_prototype(contract_prototype_v1)
    vs.add_prototype(contract_document_prototype, subpath=u'document')
    vs.add_prototype(contract_sync_prototype, subpath=u'sync')
    vs.add_prototype(qvarn.listener_prototype, auxtable=u'listener')
    vs.add_prototype(
        qvarn.notification_prototype, auxtable=u'notification')

    vs.start_version(u'v2', None)
    vs.add_prototype(contract_prototype_v2)
    vs.add_prototype(contract_document_prototype, subpath=u'document')
    vs.add_prototype(contract_sync_prototype, subpath=u'sync')
    vs.add_prototype(qvarn.listener_prototype, auxtable=u'listener')
    vs.add_prototype(qvarn.notification_prototype, auxtable=u'notification')

    vs.start_version(u'v3', None)
    vs.add_prototype(contract_prototype_v3)
    vs.add_prototype(contract_document_prototype, subpath=u'document')
    vs.add_prototype(contract_sync_prototype, subpath=u'sync')
    vs.add_prototype(qvarn.listener_prototype, auxtable=u'listener')
    vs.add_prototype(qvarn.notification_prototype, auxtable=u'notification')

    vs.start_version(u'v4', None)
    vs.add_prototype(contract_prototype_v4)
    vs.add_prototype(contract_document_prototype, subpath=u'document')
    vs.add_prototype(contract_sync_prototype, subpath=u'sync')
    vs.add_prototype(qvarn.listener_prototype, auxtable=u'listener')
    vs.add_prototype(qvarn.notification_prototype, auxtable=u'notification')

    vs.start_version(u'v5', None)
    vs.add_prototype(contract_prototype_v5)
    vs.add_prototype(contract_document_prototype, subpath=u'document')
    vs.add_prototype(contract_sync_prototype, subpath=u'sync')
    vs.add_prototype(qvarn.listener_prototype, auxtable=u'listener')
    vs.add_prototype(qvarn.notification_prototype, auxtable=u'notification')

    app = qvarn.BackendApplication()
    app.set_versioned_storage(vs)

    listener_resource = qvarn.ListenerResource()
    listener_resource.set_top_resource_path(resource_type, u'/contracts')
    app.add_resource(listener_resource)

    resource = qvarn.ListResource()
    resource.set_path(u'/contracts')
    resource.set_item_type(resource_type)
    resource.set_item_prototype(contract_prototype_current)
    resource.set_item_validator(validate_contract)
    resource.set_subitem_prototype(u'sync', contract_sync_prototype)
    resource.set_listener(listener_resource)
    app.add_resource(resource)

    file_resource = qvarn.FileResource()
    file_resource.set_item_prototype(contract_prototype_current)
    file_resource.set_top_resource_path(u'/contracts')
    file_resource.set_item_type(u'contract')
    file_resource.set_file_resource_name(u'document')
    file_resource.set_listener(listener_resource)
    app.add_resource(file_resource)

    return app.prepare_for_uwsgi()


application = setup()
