#!/usr/bin/env python2
#
# src/jobs - implement the /jobs resource
#
# Copyright 2015, 2016 Suomen Tilaajavastuu Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import os
import yaml

import qvarn


# We want to load strings as unicode, not str.
# From http://stackoverflow.com/questions/2890146/
# It seems this will be unnecessary in Python 3.
def construct_yaml_str(self, node):
    # Override the default string handling function
    # to always return unicode objects
    if node.value == 'blob':
        return buffer('')
    return self.construct_scalar(node)


yaml.SafeLoader.add_constructor(u'tag:yaml.org,2002:str', construct_yaml_str)


name = 'jobs'
path = '/etc/qvarn'
with open(os.path.join(path, name + '.yaml')) as f:
    resource_type_spec = yaml.safe_load(f)
application = qvarn.create_resource_server(resource_type_spec)
