#!/usr/bin/env python2
#
# src/orgs.py - implement the /orgs resource
#
# Copyright 2015 Suomen Tilaajavastuu Oy
# All rights reserved.


import qvarn


resource_type = u'org'


org_prototype_v0 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
}


org_prototype_v1 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
    u'country': u'',
    u'names': [u''],
    u'gov_org_ids': [
        {
            u'country': u'',
            u'org_id_type': u'',
            u'gov_org_id': u'',
        },
    ],
    u'contacts': [
        {
            u'contact_type': u'',
            u'contact_source': u'',
            u'contact_timestamp': u'',
            u'phone_number': u'',
            u'email_address': u'',
            u'full_address': u'',
            u'country': u'',
            u'address_lines': [u''],
            u'post_code': u'',
            u'post_area': u'',
        },
    ],
    u'is_luotettava_kumppani_member': False,
}


org_prototype_current = org_prototype_v2 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
    u'country': u'',
    u'names': [u''],
    u'gov_org_ids': [
        {
            u'country': u'',
            u'org_id_type': u'',
            u'gov_org_id': u'',
        },
    ],
    u'contacts': [
        {
            u'contact_type': u'',
            u'contact_roles': [u''],
            u'contact_source': u'',
            u'contact_timestamp': u'',
            u'phone_number': u'',
            u'email_address': u'',
            u'full_address': u'',
            u'country': u'',
            u'address_lines': [u''],
            u'post_code': u'',
            u'post_area': u'',
        },
    ],
    u'is_luotettava_kumppani_member': False,
}


org_sync_prototype = {
    u'sync_sources': [
        {
            u'sync_source': u'',
            u'sync_id': u'',
        },
    ],
    u'sync_revision': u'',
}


class NamelessOrg(qvarn.ValidationError):

    msg = u'Organisation {id} does not have any names'


class InvalidContactRole(qvarn.ValidationError):

    msg = u'Organisation {id} contact role is invalid'


def validate_org(obj):
    if not obj[u'names']:
        raise NamelessOrg(id=obj[u'id'])
    allowed_contact_roles = [
        u'billing'
    ]
    if u'contact_roles' in obj:
        for contact_role in obj[u'contact_roles']:
            if contact_role not in allowed_contact_roles:
                raise InvalidContactRole(id=obj[u'id'])


def setup():
    app = qvarn.BackendApplication()

    vs = qvarn.VersionedStorage()
    vs.set_resource_type(resource_type)

    vs.start_version(u'v0', None)
    vs.add_prototype(org_prototype_v0)

    vs.start_version(u'v1', None)
    vs.add_prototype(org_prototype_v1)
    vs.add_prototype(org_sync_prototype, subpath=u'sync')
    vs.add_prototype(qvarn.listener_prototype, auxtable=u'listener')
    vs.add_prototype(qvarn.notification_prototype, auxtable=u'notification')

    vs.start_version(u'v2', None)
    vs.add_prototype(org_prototype_v2)
    vs.add_prototype(org_sync_prototype, subpath=u'sync')
    vs.add_prototype(qvarn.listener_prototype, auxtable=u'listener')
    vs.add_prototype(qvarn.notification_prototype, auxtable=u'notification')

    app.set_versioned_storage(vs)

    listener_resource = qvarn.ListenerResource()
    listener_resource.set_top_resource_path(resource_type, u'/orgs')
    app.add_resource(listener_resource)

    resource = qvarn.ListResource()
    resource.set_path(u'/orgs')
    resource.set_item_type(resource_type)
    resource.set_item_prototype(org_prototype_current)
    resource.set_item_validator(validate_org)
    resource.set_subitem_prototype(u'sync', org_sync_prototype)
    resource.set_listener(listener_resource)
    app.add_resource(resource)

    return app.prepare_for_uwsgi()


application = setup()
