#!/usr/bin/env python2
#
# src/projects - implement the /projects resource
#
# Copyright 2015 Suomen Tilaajavastuu Oy
# All rights reserved.


import qvarn


resource_type = u'project'


project_prototype_v0 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
}


project_prototype_current = project_prototype_v1 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
    u'names': [u''],
    u'project_responsible_org': u'',
    u'project_responsible_person': u'',
    u'project_ids': [
        {
            u'project_id_type': u'',
            u'project_id': u'',
        },
    ],
}


project_sync_prototype = {
    u'sync_sources': [
        {
            u'sync_source': u'',
            u'sync_id': u'',
        },
    ],
    u'sync_revision': u'',
}


def validate_project(obj):
    pass


def setup():
    vs = qvarn.VersionedStorage()
    vs.set_resource_type(resource_type)

    vs.start_version(u'v0', None)
    vs.add_prototype(project_prototype_v0)

    vs.start_version(u'v1', None)
    vs.add_prototype(project_prototype_v1)
    vs.add_prototype(project_sync_prototype, subpath=u'sync')
    vs.add_prototype(qvarn.listener_prototype, auxtable=u'listener')
    vs.add_prototype(
        qvarn.notification_prototype, auxtable=u'notification')

    app = qvarn.BackendApplication()
    app.set_versioned_storage(vs)

    listener_resource = qvarn.ListenerResource()
    listener_resource.set_top_resource_path(resource_type, u'/projects')
    app.add_resource(listener_resource)

    resource = qvarn.ListResource()
    resource.set_path(u'/projects')
    resource.set_item_type(resource_type)
    resource.set_item_prototype(project_prototype_current)
    resource.set_item_validator(validate_project)
    resource.set_subitem_prototype(u'sync', project_sync_prototype)
    resource.set_listener(listener_resource)
    app.add_resource(resource)

    return app.prepare_for_uwsgi()


application = setup()
