#!/usr/bin/env python2
#
# src/reports.py - implement the /reports resource
#
# Copyright 2015 Suomen Tilaajavastuu Oy
# All rights reserved.


import unifiedapi


report_prototype = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
    u'org': u'',
    u'report_type': u'',
    u'generated_timestamp': u'',
    u'tilaajavastuu_status': u'',
}


report_sync_prototype = {
    u'sync_id': u'',
    u'sync_revision': u'',
}


listener_prototype = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
    u'notify_of_new': False,
    u'listen_on': [u'']
}


notification_prototype = {
    u'type': u'',
    u'id': u'',
    u'listener_id': u'',
    u'revision': u'',
    u'resource_id': u'',
    u'resource_revision': u'',
    u'resource_change': u'',
    u'last_modified': 0
}


class CreateReportsTables_v1(unifiedapi.StoragePreparationStep):

    def run(self, db):
        db.create_table(
            u'report',
            (u'type', unicode),
            (u'id', unicode),
            (u'revision', unicode),
            (u'org', unicode),
            (u'report_type', unicode),
            (u'generated_timestamp', unicode),
            (u'tilaajavastuu_status', unicode))

        db.create_table(
            u'report_pdf',
            (u'id', unicode),
            (u'body', buffer),
            (u'content_type', unicode))

        db.create_table(
            u'report_sync',
            (u'id', unicode),
            (u'sync_id', unicode),
            (u'sync_revision', unicode))

        db.create_table(
            u'listener',
            (u'type', unicode),
            (u'id', unicode),
            (u'revision', unicode),
            (u'notify_of_new', bool))

        db.create_table(
            u'listener_listen_on',
            (u'id', unicode),
            (u'list_pos', int),
            (u'listen_on', unicode))

        db.create_table(
            u'notification',
            (u'type', unicode),
            (u'id', unicode),
            (u'listener_id', unicode),
            (u'revision', unicode),
            (u'resource_id', unicode),
            (u'resource_revision', unicode),
            (u'resource_change', unicode),
            (u'last_modified', int))


def validate_report(obj):
    pass


if __name__ == '__main__':
    prep = unifiedapi.StoragePreparer()
    prep.add_step(u'create-reports-tables-v1', CreateReportsTables_v1())

    resource = unifiedapi.ListResource()
    resource.set_path(u'/reports')
    resource.set_item_type(u'report')
    resource.set_item_prototype(report_prototype)
    resource.set_item_validator(validate_report)
    resource.set_file_resource_name(u'pdf')
    resource.set_subitem_prototype(u'sync', report_sync_prototype)
    resource.set_listener_prototype(listener_prototype)
    resource.set_notification_prototype(notification_prototype)
    resource.set_storage_preparer(prep)

    app = unifiedapi.BackendApplication()
    app.set_resource(resource)
    app.run()
