#!/usr/bin/env python2
#
# src/reports.py - implement the /reports resource
#
# Copyright 2015 Suomen Tilaajavastuu Oy
# All rights reserved.


import unifiedapi


resource_type = u'report'


report_prototype_v0 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
}


report_prototype_current = report_prototype_v1 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
    u'org': u'',
    u'report_type': u'',
    u'generated_timestamp': u'',
    u'tilaajavastuu_status': u'',
}


report_pdf_prototype = {
    u'body': buffer(''),
    u'content_type': u'',
}


report_sync_prototype = {
    u'sync_sources': [
        {
            u'sync_source': u'',
            u'sync_id': u'',
        },
    ],
    u'sync_revision': u'',
}


def validate_report(obj):
    pass


def setup():
    vs = unifiedapi.VersionedStorage()
    vs.set_resource_type(resource_type)

    vs.start_version(u'v0', None)
    vs.add_prototype(report_prototype_v0)

    vs.start_version(u'v1', None)
    vs.add_prototype(report_prototype_v1)
    vs.add_prototype(report_pdf_prototype, subpath=u'pdf')
    vs.add_prototype(report_sync_prototype, subpath=u'sync')
    vs.add_prototype(unifiedapi.listener_prototype, auxtable=u'listener')
    vs.add_prototype(
        unifiedapi.notification_prototype, auxtable=u'notification')

    app = unifiedapi.BackendApplication()
    app.set_versioned_storage(vs)

    listener_resource = unifiedapi.ListenerResource()
    listener_resource.set_top_resource_path(resource_type, u'/reports')
    app.add_resource(listener_resource)

    resource = unifiedapi.ListResource()
    resource.set_path(u'/reports')
    resource.set_item_type(resource_type)
    resource.set_item_prototype(report_prototype_current)
    resource.set_item_validator(validate_report)
    resource.set_subitem_prototype(u'sync', report_sync_prototype)
    resource.set_listener(listener_resource)
    app.add_resource(resource)

    file_resource = unifiedapi.FileResource()
    file_resource.set_item_prototype(report_prototype_current)
    file_resource.set_top_resource_path(u'/reports')
    file_resource.set_item_type(resource_type)
    file_resource.set_file_resource_name(u'pdf')
    file_resource.set_listener(listener_resource)
    app.add_resource(file_resource)

    return app.prepare_for_uwsgi()


application = setup()
