#!/usr/bin/env python2
#
# src/report_accesses - implement the /report_accesses resource
#
# Copyright 2015, 2016 Suomen Tilaajavastuu Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import qvarn


report_access_prototype_v0 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
}


report_access_prototype_current = report_access_prototype_v1 = {
    u'type': u'',
    u'id': u'',
    u'revision': u'',
    u'client_id': u'',
    u'customer_id': u'',
    u'org_id': u'',
    u'report_id': u'',
    u'arkisto_id': u'',
    u'access_time': u'',
}


resource_type_spec = {
    u'path': u'/report_accesses',
    u'type': u'report_access',
    u'versions': [
        {
            u'version': u'v0',
            u'prototype': report_access_prototype_v0,
        },
        {
            u'version': u'v1',
            u'prototype': report_access_prototype_v1,
        },
    ],
}

application = qvarn.create_resource_server(resource_type_spec)
