#!/usr/bin/env python2
#
# src/version - implement the /version resource
#
# Copyright 2015 Suomen Tilaajavastuu Oy
# All rights reserved.


import unifiedapi


def version():
    return {
        'api': {
            'version': '1.0',
        },
        'implementation': {
            'version': 'see git',
            'name': 'unified-api-backend',
        },
    }


def main():
    app = unifiedapi.BackendApplication()

    vs = unifiedapi.VersionedStorage()
    vs.set_resource_type(u'version')
    app.set_versioned_storage(vs)

    resource = unifiedapi.SimpleResource()
    resource.set_path(u'/version', version)
    app.add_resource(resource)

    app.run()


if __name__ == '__main__':
    main()
