#!/usr/bin/env python2
#
# src/version - implement the /version resource
#
# Copyright 2015, 2016 Suomen Tilaajavastuu Oy
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import qvarn


def version():
    return {
        'api': {
            'version': '1.0',
        },
        'implementation': {
            'version': 'see git',
            'name': 'Qvarn',
        },
    }


def setup():
    app = qvarn.BackendApplication()

    vs = qvarn.VersionedStorage()
    vs.set_resource_type(u'version')
    app.set_versioned_storage(vs)

    resource = qvarn.SimpleResource()
    resource.set_path(u'/version', version)
    app.add_resource(resource)

    return app.prepare_for_uwsgi()


application = setup()
